site_name: Nix Guides
site_url: https://moretea.github.io/nix-guides/
repo_url: https://github.com/moretea/nix-guides/

docs_dir: 'guides'
strict: true

markdown_extensions:
  - footnotes
  - codehilite:
      linenums: True
  - admonition

pages:
  - Home: index.md
  - Overview: overview.md
  - Tutorial: getting-started-tutorial.md
  - Packaging:
    - Background: packaging/background.md
